services:
  super-app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5000:3000'
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo
    environment:
      - MONGO_URI=mongodb:localhost:27018/docker
    volumes:
      - mongo_data:/var/lib/mongodb/data
    container_name: mongo:test
    ports:
      - '27018:27017'
    restart: unless-stopped

volumes:
  mongo_data:
